### PR TITLE
Smack 4.3.4

### PR DESCRIPTION
**Pull request by Flowdalic**
I took the liberty to update to the latest Smack version.

I am not sure why `connection.disconnect()` was commented out, you really should always disconnect the connection once you drop all references to the instance. Hence I added it again.

### CODE REVIEW

**Comment by no-go** [comment]
I think the disconnect cause troubble in my service... but I did not use finally()

**Comment by no-go** [comment]
I think I had already decided on an older smack version because I couldn't find any working new examples. I tested your code, and unfortunately it didn't send me any messages. as sender i took an account from blah.im and receiver was a user at patchcord.be

there were no error messages or warnings. but log in services is a thing in itself, it seems to me.

i'm sorry for your efforts. i've only taken over a part of it now. it's also a pity that smack doesn't care about downward compatibility.

**Comment by Flowdalic** [comment]
> there were no error messages or warnings. but log in services is a thing in itself, it seems to me.

I am not sure if I can follow, the culprit should be easily identifiable when debugging the issue.

> i've only taken over a part of it now. it's also a pity that smack doesn't care about downward compatibility.

That is not entirely true: Smack *does* care about backwards compatibility, all patchlevel releases can be used as drop-in replacement. But APIs involve, the Smack version you use(d), 4.1.6 is more than 3 years old, you can not expect an API to stay absolutely stable for multiple years, sometimes developers have to change things. And Smack tries to stay as backwards compatible as possible. For example in this case I think the Smack version bump could have been done without touching any user code. I just took the liberty to rewrite it a bit in an attempt to improve it.

> i'm sorry for your efforts.

No worries, it was a low-hanging fruit and I just wanted the project to use a Smack version without known security vulnerabilities.

**Comment by no-go** [comment]
Thank you for your support. maybe in the future I will try to upgrade. Actually study/master thesis and job burns my brain a little bit. 🤯

**Pull request merged**
